.TH MUNDUS 1 "February 27, 2011"
.SH NAME
mundus \- A software to clean your /home folder.
.SH SYNOPSIS
.B mundus
.SH DESCRIPTION
Mundus can keep your /home folder clean by looking for uninstalled software that left configuration files.
It can automatically or manually backup those files in case you need them later.
.br
.SH AUTHOR
Mundus was written by sebikul <sebikul@gmail.com>
.PP
This manual page was written by Andrea Colangelo <warp10@ubuntu.com>,
for the Ubuntu project (and may be used by others).